### ISSUE TITLE
No Render

### ISSUE THREAD

**Issue by osaaso3** [plbonneville/BlazorInteractive#4]
Hi
the IncrementCount inside online JupyterLab myBinder doesn't work and currentCount remains 0 when I press the famus Counter button.

**Comment by plbonneville** [comment]
Hi @osaaso3 ,

The blazor kernel should work in binders hosted on mybinder.org. Make sure you have the correct NuGet.config file. You can try with the one found here https://github.com/dotnet/interactive

Currently this package only renders the HTML generated from the razor components (blazor code). In addition, it adds a reference the components so that they can be used in other code cells.

I’ll open another issue to research how to host a blazor application in an interactive notebook.

To help clarify the current state of this project I’ve added a diagram of the sequence of commands and events to the [README.md](https://github.com/plbonneville/BlazorInteractive/blob/main/README.md)

**Comment by osaaso3** [comment]
Thanks
